### ISSUE TITLE
tm2scatch が読み込まれた回数を計測したい

### ISSUE THREAD

**Issue by champierre** [champierre/tm2scratch#16]
scratch-gui > src > lib > analytics.js

をいじるとできるのかもしれない。

**Comment by champierre** [comment]
index.html の head 内で ga タグを挿入、scratch-vm/src/extension-support/extension-manger.js#163 に以下を追加することで対応

```
            gtag('event', 'load_extension', {
              'event_category': extensionURL
            });
```

<img width="1264" alt="スクリーンショット 2020-03-08 18 09 19" src="https://user-images.githubusercontent.com/10215/76160278-0cf58280-616c-11ea-92c8-adfa66e51d7d.png">

**Comment by champierre** [comment]
@ukkari クローズしますね

**Comment by ukkari** [comment]
LGTM. Thanks!
